// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnrcudXOBD3TeWeCYF-dlPa-zv1dLUGh4',
    appId: '1:287751604152:web:91812c33afc50c48c4314d',
    messagingSenderId: '287751604152',
    projectId: 'finalyear-328b3',
    authDomain: 'finalyear-328b3.firebaseapp.com',
    databaseURL: 'https://finalyear-328b3-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'finalyear-328b3.firebasestorage.app',
    measurementId: 'G-E4VJGRLKJ9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_SHijE5LGd6u2YF1aRk66qPQkeZhmvnU',
    appId: '1:287751604152:android:50cb9b846e8a9625c4314d',
    messagingSenderId: '287751604152',
    projectId: 'finalyear-328b3',
    databaseURL: 'https://finalyear-328b3-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'finalyear-328b3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAU5W8M3zBPImoPb9B4DHUj0pbyftGXHXY',
    appId: '1:287751604152:ios:957de95ca5d47837c4314d',
    messagingSenderId: '287751604152',
    projectId: 'finalyear-328b3',
    databaseURL: 'https://finalyear-328b3-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'finalyear-328b3.firebasestorage.app',
    iosBundleId: 'com.example.finalYearProjectTest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAU5W8M3zBPImoPb9B4DHUj0pbyftGXHXY',
    appId: '1:287751604152:ios:957de95ca5d47837c4314d',
    messagingSenderId: '287751604152',
    projectId: 'finalyear-328b3',
    databaseURL: 'https://finalyear-328b3-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'finalyear-328b3.firebasestorage.app',
    iosBundleId: 'com.example.finalYearProjectTest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBnrcudXOBD3TeWeCYF-dlPa-zv1dLUGh4',
    appId: '1:287751604152:web:d95da69dbeb03ba9c4314d',
    messagingSenderId: '287751604152',
    projectId: 'finalyear-328b3',
    authDomain: 'finalyear-328b3.firebaseapp.com',
    databaseURL: 'https://finalyear-328b3-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'finalyear-328b3.firebasestorage.app',
    measurementId: 'G-CV30BW9Z8M',
  );
}
